approvals:
  minimum: 2
  groups:
    - name: approvers 
      minimum: 2
      from:
        - EsseLowNitro
        - fiftydinar
        - RoyalOughtness
        - mintpilo
        - mkkvcs
        - RKNF404
        - Rubiginosa
        - ShadowSlayer1441
        - spaceoden
        - TheHooly
        - WavyEbuilder