repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,patch"]
        exclude: "\\.patch$"

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # v1.29.0
    hooks:
      - id: zizmor
        exclude: "^\\.github/workflows/config/linkspector\\.yml$"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 65dbdb59d2f2d9c3bdc343c566821ad3319ddaa3 # v0.16.3
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: 757b1b0ee6dce6b1541bbe70218055b62aaeb051 # v0.0.72
    hooks:
      - id: ty
        args: [--isolated]

  - repo: local
    hooks:
      # We use a local hook rather than the official ShellCheck pre-commit hook
      # because the official hook runs as a container image, which won't run on
      # secureblue in the default system configuration.
      - id: shellcheck
        name: ShellCheck
        description: "Shell script linter: https://www.shellcheck.net/"
        entry: shellcheck
        language: system
        types: [text]
        types_or: [bash, bats, shell]

      - id: shell-script-shebangs
        name: check script shebangs
        description: "Check shell script shebang lines are normalized"
        entry: awk -f tools/check-shell-script-shebangs.awk
        language: system
        types: [text]
        types_or: [bash, bats, shell]
