repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,patch']

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # v1.26.1
    hooks:
      - id: zizmor
        exclude: "^\\.github/workflows/config/linkspector\\.yml$"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56 # v0.15.20
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: 73e808ce6d5bdbf3bf7950ef1a8c0a035c44a2c6 # v0.0.55
    hooks:
      - id: ty
        args: [--isolated]

  - repo: local
    hooks:
      # We use a local hook rather than the official ShellCheck pre-commit hook
      # because the official hook runs as a container image, which won't run on
      # secureblue in the default system configuration.
      - id: shellcheck
        name: ShellCheck
        description: "Shell script linter: https://www.shellcheck.net/"
        entry: shellcheck
        language: system
        types: [text]
        types_or: [bash, bats, shell]

      - id: shell-script-shebangs
        name: check script shebangs
        description: "Check shell script shebang lines are normalized"
        entry: awk -f tools/check-shell-script-shebangs.awk
        language: system
        types: [text]
        types_or: [bash, bats, shell]
