#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2025 Universal Blue
# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_REF_NAME=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split("/")[-1]')
if echo "$RPM_OSTREE_STATUS" | grep -q 'hardened:'; then
    IMAGE_TAG=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split(":")[-1]')
else
    IMAGE_TAG='ERROR-IMAGE-TAG-MISSING'
fi
TIP=''

IMAGE_DATE=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0].timestamp')
CURRENT_SECONDS=$(date +%s)
DIFFERENCE=$((CURRENT_SECONDS - IMAGE_DATE))
WEEK=$((7 * 24 * 60 * 60))

readarray -t imageTypes < <(jq -r '.imageTypes[]' /usr/libexec/deprecated-images.json)
isDeprecated=false
for imageType in "${imageTypes[@]}"; do
    if [[ "$IMAGE_REF_NAME" == *"$imageType"* ]]; then
        isDeprecated=true
        break
    fi
done


reset=$'\e[0m'
bold=$'\e[1m'
slight_red=$'\e[48;2;48;48;48m\e[38;2;245;86;71m'
link=$'\e[38;2;23;118;122m'
header=$'\e[1;38;5;228m\e[48;5;63m'

if $isDeprecated; then
    TIP="${bold}You are on a deprecated image, rebase: ${reset}${link}https://github.com/secureblue/secureblue/blob/live/files/system/usr/libexec/deprecated-images.json.md${reset}"
elif mokutil --list-enrolled >/dev/null 2>&1 && ! mokutil --list-enrolled | grep -q "secureblue secureboot key"; then
    TIP="${bold}Secureboot key is not enrolled! Run ${reset}${slight_red} ujust enroll-secureblue-secure-boot-key ${reset}${bold} to resolve this issue. More information: ${reset}${link}https://secureblue.dev/faq#new-key${reset}"
elif [ "$IMAGE_TAG" == 'ERROR-IMAGE-TAG-MISSING' ]; then
    TIP="${bold}You are missing an image tag, which is unsupported by secureblue. Rebase to the ${reset}${slight_red} latest ${reset}${bold} tag to ensure you continue to receive updates.${reset}"
elif [ "$IMAGE_TAG" != "latest" ]; then
    TIP="${bold}You are on a specific tag, which is unsupported by secureblue. Rebase to the ${reset}${slight_red} latest ${reset}${bold} tag to ensure you continue to receive updates.${reset}"
elif [ "$DIFFERENCE" -ge "$WEEK" ]; then
    TIP="${bold}Your current image is over 1 week old, run ${reset}${slight_red} ujust update-system ${reset}${reset}"
fi

cat << EOF

  ${header} Welcome to secureblue! ${reset}

  Your image is: ${slight_red} ${IMAGE_REF_NAME} ${reset}

   >. Command                    │ Description                                
  ───────────────────────────────┼────────────────────────────────────────────
   ${slight_red} ujust --choose ${reset}              │ List all available commands
   ${slight_red} ujust toggle-user-motd ${reset}      │ Toggle this banner on/off
   ${slight_red} brew help ${reset}                   │ Manage command line packages
EOF
if [ -n "$TIP" ]; then
    echo
    echo -e "  ${TIP}"
fi
cat << EOF

  • ${bold}Release notifications:${reset} ${link}https://secureblue.dev/faq#release${reset}
  • ${bold}Report an issue:${reset} ${link}https://github.com/secureblue/secureblue/issues${reset}
  • ${bold}FAQ:${reset} ${link}https://secureblue.dev/faq${reset}
  • ${bold}Donate:${reset} ${link}https://secureblue.dev/donate${reset}
  • ${bold}Discord:${reset} ${link}https://discord.gg/qMTv5cKfbF${reset}

EOF
