#!/usr/bin/bash

# Copyright 2025 Universal Blue
# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_REF_NAME=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split("/")[-1]')
if echo "$RPM_OSTREE_STATUS" | grep -q 'hardened:'; then
    IMAGE_TAG=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split(":")[-1]')
else
    IMAGE_TAG='ERROR-IMAGE-TAG-MISSING'
fi
TIP=""

IMAGE_DATE=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0].timestamp')
CURRENT_SECONDS=$(date +%s)
DIFFERENCE=$((CURRENT_SECONDS - IMAGE_DATE))
WEEK=$((7 * 24 * 60 * 60))

readarray -t imageTypes < <(jq -r '.imageTypes[]' /usr/libexec/deprecated-images.json)
isDeprecated=false
for imageType in "${imageTypes[@]}"; do
    if [[ "$IMAGE_REF_NAME" == *"$imageType"* ]]; then
        isDeprecated=true
        break
    fi
done

if $isDeprecated; then
    TIP='**You are on a deprecated image,** [rebase:](https://github.com/secureblue/secureblue/blob/live/files/system/usr/libexec/deprecated-images.json.md)'
elif mokutil --list-enrolled >/dev/null 2>&1 && ! mokutil --list-enrolled | grep -q "secureblue secureboot key"; then
    TIP='**Secureboot key is not enrolled! Run `ujust enroll-secureblue-secure-boot-key` to resolve this issue.** [More information](https://secureblue.dev/faq#new-key)'
elif [ "$IMAGE_TAG" == 'ERROR-IMAGE-TAG-MISSING' ]; then
    TIP='**You are missing an image tag, which is unsupported by secureblue. Rebase to the `latest` tag to ensure you continue to receive updates.**'
elif [ "$IMAGE_TAG" != "latest" ]; then
    TIP='**You are on a specific tag, which is unsupported by secureblue. Rebase to the `latest` tag to ensure you continue to receive updates.**'
elif [ "$DIFFERENCE" -ge "$WEEK" ]; then
    TIP='**Your current image is over 1 week old, run `rpm-ostree upgrade`.**'
else
    TIP='**For secureblue release notifications,** [subscribe:](https://secureblue.dev/faq#releases)'
fi

RESET='\e[0m'
BOLD='\e[1m'
SLIGHT_RED='\e[48;2;48;48;48m\e[38;2;245;86;71m'
LINK='\e[38;2;23;118;122m'
HEADER='\e[1;38;5;228m\e[48;5;63m'

echo
echo -e "  ${HEADER} Welcome to secureblue! ${RESET}\n"
echo -e "  Your image is: ${SLIGHT_RED} ${IMAGE_REF_NAME} ${RESET}\n"
echo "   >. Command                    │ Description                                "
echo "  ───────────────────────────────┼────────────────────────────────────────────"
echo -e "   ${SLIGHT_RED} ujust --choose ${RESET}              │ List all available commands"
echo -e "   ${SLIGHT_RED} ujust toggle-user-motd ${RESET}      │ Toggle this banner on/off"
echo -e "   ${SLIGHT_RED} brew help ${RESET}                   │ Manage command line packages"
echo
echo -e "  • ${BOLD}Release notifications:${RESET} ${LINK}https://secureblue.dev/faq#release${RESET}"
echo -e "  • ${BOLD}Report an issue:${RESET} ${LINK}https://github.com/secureblue/secureblue/issues${RESET}"
echo -e "  • ${BOLD}FAQ:${RESET} ${LINK}https://secureblue.dev/faq${RESET}"
echo -e "  • ${BOLD}Donate:${RESET} ${LINK}https://secureblue.dev/donate${RESET}"
echo -e "  • ${BOLD}Discord:${RESET} ${LINK}https://discord.gg/qMTv5cKfbF${RESET}"
