#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

fwupdmgr get-updates --json | jq -e '.Devices != []' > /dev/null
