#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

FWUPD_STATUS=$(/usr/bin/fwupdmgr get-updates --json)
EXPECTED_STATUS=$(/usr/bin/cat <<EOF
{
  "Devices" : []
}
EOF
)

if [[ "$FWUPD_STATUS" != "$EXPECTED_STATUS" ]]; then
    # Exit success if update available.
    exit 0
else
    exit 1
fi
