#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

FWUPD_DEVICE_COUNT=$(fwupdmgr get-updates --json | jq '.Devices | length')

if [[ "$FWUPD_DEVICE_COUNT" -eq 0 ]]; then
    exit 0
else
    exit 1
fi
