#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright 2025 Universal Blue
# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_REF_NAME=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split("/")[-1]')

readarray -t imageTypes < <(jq -r '.imageTypes[]' /usr/libexec/deprecated-images.json)

for imageType in "${imageTypes[@]}"; do
    if [[ "$IMAGE_REF_NAME" == *"$imageType"* ]]; then
        exit 0
    fi
done

exit 1
