#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -oue pipefail

status="$(rpm-ostree status)"

if [[ "$status"  =~ SecAdvisories:.*(important|critical) ]]; then
	case "$(notify-send --urgency=critical \
		--app-name="secureblue" \
		--action="Reboot" \
		"A major security vulnerability has been patched" \
		"Please reboot to run the updated system")" in
			"0")
				systemctl reboot ;;

	esac

elif [[ "$status"  =~ SecAdvisories:.*(unknown severity|low|moderate) ]]; then
	case "$(notify-send --urgency=normal \
		--expire-time=5000 \
		--app-name="secureblue" \
		--action="Reboot" \
		"A security vulnerability has been patched" \
		"Please reboot to run the updated system")" in
			"0")
				systemctl reboot ;;
	esac
fi
