#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

in_progress_indicator=~/.cache/secureblue-flatpak-setup-in-progress
if [[ ! -f "${in_progress_indicator}" ]]; then
    notify-send -a 'secureblue' -i 'dialog-information' -u normal 'Provisioning core flatpaks, please wait...'
fi
touch "${in_progress_indicator}"

flatpak remote-add --if-not-exists --user --subset=verified --title='Flathub Verified' flathub-verified https://dl.flathub.org/repo/flathub.flatpakrepo
ujust harden-flatpak

flatpak install --user -y --noninteractive flathub-verified com.github.tchx84.Flatseal

notify-send -a 'secureblue' -i 'dialog-information' -u normal 'Flatpak provisioning completed.'
rm -f "${in_progress_indicator}"
