#!/usr/bin/env bash

# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

set -euo pipefail

selection=$(notify-send -A 'info=More Information' -a 'secureblue' -i 'dialog-warning' 'Secureboot key is not enrolled!' 'Run <i>ujust enroll-secureblue-secure-boot-key</i> to resolve this issue.' -u critical)

if [[ $selection == "info" ]]; then
  trivalent "https://secureblue.dev/faq#new-key"
fi
