#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

status="$(rpm-ostree status 2>/dev/null)"
db_diff="$(rpm-ostree db diff 2>&1)"
trivalent_updated="false"
kernel_updated="false"
if [[ "$db_diff" == *"pending deployment"* ]]; then
  if [[ "$db_diff" == *"trivalent "* ]]; then
    trivalent_updated="true"
  fi
  if [[ "$db_diff" == *"kernel "* ]]; then
    kernel_updated="true"
  fi
fi

notify_critical() {
  notify-send --urgency=critical \
    --app-name="secureblue" \
    --action="Reboot" \
    "A major security vulnerability has been patched" \
    "Please reboot to run the updated system"
}

notify_normal() {
  notify-send --urgency=normal \
    --expire-time=5000 \
    --app-name="secureblue" \
    --action="Reboot" \
    "A security vulnerability has been patched" \
    "Please reboot to run the updated system"
}

if [[ "$trivalent_updated" == "true" || "$status" =~ SecAdvisories:.*critical ]]; then
  if [[ "$(notify_critical)" == "0" ]]; then
    systemctl reboot
  fi
elif [[ "$kernel_updated" == "true" || "$status" =~ SecAdvisories:.*(important|unknown severity) ]]; then
  if [[ "$(notify_normal)" == "0" ]]; then
    systemctl reboot
  fi
fi
