contact_links:
  - name: General Inquiry
    url: https://discord.gg/gNr3Kbks34
    about: Project questions, support, and discussion with the community
# disable blank issue creation
blank_issues_enabled: false