#!/bin/bash

# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

set -oue pipefail

status="$(rpm-ostree status)"

show-rpm-ostree-status() {
	tmpfile="$(mktemp -t rpm-ostree-status-XXXXXXXXXX.txt)"
	rpm-ostree status --verbose > "$tmpfile"
	xdg-open "$tmpfile"
}

if [[ "$status"  =~ SecAdvisories:.*(moderate|important|critical) ]]; then
	case "$(notify-send --urgency=critical \
		--app-name="secureblue" \
		--action="Reboot" \
		--action="See CVE Details" \
		"A major security vulnerability has been patched" \
		"Please reboot to run the updated system")" in
			"0")
				systemctl reboot ;;

			"1")
				show-rpm-ostree-status ;;
	esac

elif [[ "$status"  =~ SecAdvisories:.*(unknown severity|low) ]]; then
	case "$(notify-send --urgency=normal \
		--expire-time=5000 \
		--app-name="secureblue" \
		--action="Reboot" \
		--action="See CVE Details" \
		"A security vulnerability has been patched" \
		"Please reboot to run the updated system")" in
			"0")
				systemctl reboot ;;

			"1")
				show-rpm-ostree-status ;;
	esac
fi
