#!/usr/bin/env bash
set -euo pipefail

[[ -d /home/linuxbrew/.linuxbrew && $- == *i* ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Install required brew packages
/home/linuxbrew/.linuxbrew/bin/brew install fzf gum glow

