#!/usr/bin/env bash

# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

set -euo pipefail

# Remove vestigial authselect overrides from Anaconda
cp /usr/etc/authselect/system-auth /etc/authselect/system-auth
cp /usr/etc/authselect/fingerprint-auth /etc/authselect/fingerprint-auth
cp /usr/etc/authselect/dconf-db /etc/authselect/dconf-db
cp /usr/etc/authselect/authselect.conf /etc/authselect/authselect.conf

flatpak remote-delete --system --force fedora || true
flatpak remote-delete --user --force fedora || true
flatpak remote-delete --system --force flathub || true
flatpak remote-delete --user --force flathub || true
flatpak remove --system --noninteractive --all

# Ensure we are on signed
RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_BASE_STRING=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty')
echo "Current image base: $IMAGE_BASE_STRING"
if [[ "$IMAGE_BASE_STRING" == *"ostree-image-signed"* ]]; then
    echo "Already on signed. Exiting..."
    exit 0
fi

IMAGE_REF_NAME=${IMAGE_BASE_STRING##*/}
echo "Rebasing to $IMAGE_REF_NAME"
rpm-ostree rebase "ostree-image-signed:docker://ghcr.io/secureblue/$IMAGE_REF_NAME"

