#!/usr/bin/bash

# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Remove vestigial authselect overrides from Anaconda
cp /usr/share/secureblue/etc/authselect/system-auth /etc/authselect/system-auth
cp /usr/share/secureblue/etc/authselect/fingerprint-auth /etc/authselect/fingerprint-auth
cp /usr/share/secureblue/etc/authselect/dconf-db /etc/authselect/dconf-db
cp /usr/share/secureblue/etc/authselect/authselect.conf /etc/authselect/authselect.conf

# Remove firewalld zone override from Anaconda
cp /usr/share/secureblue/etc/firewalld/zones/FedoraWorkstation.xml /etc/firewalld/zones/FedoraWorkstation.xml || true
cp /usr/share/secureblue/etc/firewalld/zones/FedoraServer.xml /etc/firewalld/zones/FedoraServer.xml || true

# Undo chronyd timeserver configuration from Anaconda, which is empty sometimes.
cp /usr/share/secureblue/etc/chrony.conf /etc/chrony.conf

if command -v flatpak &> /dev/null
then
    flatpak remote-delete --system --force fedora || true
    flatpak remote-delete --user --force fedora || true
    flatpak remote-delete --system --force fedora-testing || true
    flatpak remote-delete --user --force fedora-testing || true
    flatpak remote-delete --system --force flathub || true
    flatpak remote-delete --user --force flathub || true
    flatpak remove --system --noninteractive --all || true
fi

if [[ ! -f "/usr/bin/rpm-ostree" ]]; then
    # If on UKI image, we need to exit success early otherwise securebluecleanup
    # will fail and keep retrying and running the above steps.
    exit 0
fi

# Ensure we are on signed
RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_BASE_STRING=$(echo "${RPM_OSTREE_STATUS}" | jq -r '.deployments[0]."container-image-reference" // empty')
echo "Current image base: ${IMAGE_BASE_STRING}"
if [[ "${IMAGE_BASE_STRING}" == *"ostree-image-signed"* ]]; then
    echo "Already on signed. Exiting..."
    exit 0
fi

IMAGE_REF_NAME=${IMAGE_BASE_STRING##*/}
echo "Rebasing to ${IMAGE_REF_NAME}"
rpm-ostree rebase "ostree-image-signed:docker://ghcr.io/secureblue/${IMAGE_REF_NAME}"
