server:
	# Run daemon unprivileged
	username: ""
	use-systemd: yes
	do-daemonize: no
	ip-transparent: no
	ip-freebind: no

	# Hardening
	use-caps-for-id: yes
	harden-large-queries: yes

	# Performance
	prefetch: yes
	prefetch-key: yes
