server:
	# Do not try to setuid/setgid.
	username: ""

	# Use systemd sockets, do not fork.
	use-systemd: yes
	do-daemonize: no

	# Stop unbound from binding to non-local interfaces.
	ip-transparent: no
	ip-freebind: no
