# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

# Ensure user fonts are correctly labeled. This ensures that Trivalent's
# SELinux policy permits loading the fonts.
Z %h/.local/share/fonts
