# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

# Disable QEMU core dumps to work around this bug:
# https://github.com/secureblue/secureblue/issues/1054
d %h/.config/libvirt            0700 - - -
f %h/.config/libvirt/qemu.conf  0600 - - - max_core = 0\n
