#!/usr/bin/python3

# SPDX-FileCopyrightText: Copyright 2026 Commenter25
#
# SPDX-License-Identifier: Apache-2.0

"""Constructs block-record's PipeWire config file, and overwrites the old one."""

import subprocess
from json import dump as write_json

from . import CONFIG, PIPEWIRE_CONFIG_PATH, SCRIPT_CONFIG_PATH, print_tty


def write_pipewire_config() -> int:
    """Writes to the PipeWire config file."""

    def finalize() -> int:
        # we write the real config now that we know changes are applied
        print_tty("You may hear a momentary stutter, this is normal.")
        return subprocess.run(
            ["/usr/bin/systemctl", "restart", "--user", "pipewire-pulse"], check=True
        ).returncode

    none_blocked = len(CONFIG.blocked) == 0 and not CONFIG.block_by_default
    none_allowed = len(CONFIG.allowed) == 0 and CONFIG.block_by_default

    if none_blocked:
        PIPEWIRE_CONFIG_PATH.unlink(missing_ok=True)
        return finalize()

    matches: list[dict[str, str]] | None = None
    key = "pipewire.access.portal.app_id"

    if none_allowed:
        matches = [{"pipewire.client.access": "flatpak"}]
    elif CONFIG.block_by_default:
        # they Want you to do this by having multiple keys
        # but python is sane and doesn't allow that in dicts
        # so the alternative is this ugly janky regex :)
        combined = "|".join(CONFIG.allowed)
        matches = [{key: f"!~({combined})"}]
    else:
        matches = [{key: app} for app in CONFIG.blocked]

    pipewire_config = {
        "pulse.rules": [{"matches": matches, "actions": {"quirks": ["block-record-stream"]}}]
    }

    PIPEWIRE_CONFIG_PATH.parent.mkdir(0o700, parents=True, exist_ok=True)
    PIPEWIRE_CONFIG_PATH.touch(0o600, exist_ok=True)
    with PIPEWIRE_CONFIG_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "# This file is automatically generated by the command ujust block-record\n"
            "# Any changes will be overwritten! Edit the following file instead:\n"
            f"# {SCRIPT_CONFIG_PATH}\n"
        )
        write_json(pipewire_config, f, separators=(",", ":"))
    return finalize()
