# Add more distros and then use:
# ujust toolbox-assemble prompt create
# This will replace your toolboxes in place
[rhel-toolbox-8]
image=registry.access.redhat.com/ubi8/toolbox:latest

[rhel-toolbox-9]
image=registry.access.redhat.com/ubi9/toolbox:latest

[fedora-toolbox]
image=ghcr.io/ublue-os/fedora-toolbox:latest