[Service]
# Do not start service if Xwayland is disabled
ExecCondition=/usr/bin/bash -c '! [ -f /etc/systemd/user/plasma-kwin_wayland.service.d/override.conf ] || /usr/bin/grep -qs "[[:blank:]]--xwayland\>" /etc/systemd/user/plasma-kwin_wayland.service.d/override.conf'
