# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

# This file is intentionally empty.
#
# It is here to override /usr/lib/tmpfiles.d/homebrew.conf to prevent
# the Homebrew installation from being recreated for users who have
# already opted out of Homebrew.
#
# For users who have not opted out of installing Homebrew, this file
# will be automatically deleted by brew-setup-migration.service.
#
# This file can be removed from the secureblue images after enough time
# has passed that users should all be migrated to the new Homebrew setup
# method based on tmpfiles.d.
