name: build-testing

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: "00 6 * * *" # build at 6:00 UTC every day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-testing:
    name: Build UKI images (testing)
    runs-on: ubuntu-26.04
    permissions:
      actions: write # needed to kick off job
    steps:
      - run: gh workflow run build-all.yml --repo "${GITHUB_REPOSITORY}" --ref testing
        env:
          GH_TOKEN: ${{ github.token }}
