# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: build-secureblue
permissions: {}
on:
  schedule:
    - cron: "00 6 * * *" # build at 6:00 UTC every day 
    
  push:
    branches-ignore: # don't rebuild for dependabot
      - 'dependabot/**'
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  workflow_dispatch: # allow manually triggering builds

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  phase1-main:
    name: Build main images
    if: github.triggering_actor == 'royaloughtness' || ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'push' }} 
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # general
          - general/recipe-silverblue-main.yml
          - general/recipe-kinoite-main.yml
          - general/recipe-sericea-main.yml
          - general/recipe-cosmic-main.yml
          # server
          - securecore/recipe-securecore-main.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets: inherit

  phase2-nvidia:
    name: Build nvidia images
    if: github.triggering_actor == 'royaloughtness' || ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'push' }} 
    needs: phase1-main
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # general
          - general/recipe-silverblue-nvidia.yml
          - general/recipe-silverblue-nvidia-open.yml
          - general/recipe-kinoite-nvidia.yml
          - general/recipe-kinoite-nvidia-open.yml
          - general/recipe-sericea-nvidia.yml
          - general/recipe-sericea-nvidia-open.yml
          - general/recipe-cosmic-nvidia.yml
          - general/recipe-cosmic-nvidia-open.yml
          # server
          - securecore/recipe-securecore-nvidia.yml
          - securecore/recipe-securecore-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets: inherit

  phase3-zfs:
    name: Build zfs images
    if: github.triggering_actor == 'royaloughtness' || ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'push' }}
    needs: phase2-nvidia
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # server with zfs
          - securecore/recipe-securecore-zfs-main.yml
          - securecore/recipe-securecore-zfs-nvidia.yml
          - securecore/recipe-securecore-zfs-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets: inherit