# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: build

permissions: {}

on:
  schedule:
    - cron: "00 6 * * *" # build at 6:00 UTC every day

  push:
    branches-ignore: # don't rebuild for dependabot
      - 'dependabot/**'
      - 'create-pull-request/**'
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  workflow_dispatch: # allow manually triggering builds
    inputs:
      clear-plan:
        description: 'Clear previous layer plan?'
        type: boolean
        required: true
        default: false

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  silverblue-main:
    name: Build silverblue main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-silverblue-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  silverblue-main-sealed:
    name: Build silverblue main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: silverblue-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.silverblue-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.silverblue-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.silverblue-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.silverblue-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

  kinoite-main:
    name: Build kinoite main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-kinoite-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  kinoite-main-sealed:
    name: Build kinoite main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: kinoite-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.kinoite-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.kinoite-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.kinoite-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.kinoite-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

  sericea-main:
    name: Build sericea main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-sericea-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  sericea-main-sealed:
    name: Build sericea main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: sericea-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.sericea-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.sericea-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.sericea-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.sericea-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

  cosmic-main:
    name: Build cosmic main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-cosmic-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  cosmic-main-sealed:
    name: Build cosmic main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: cosmic-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.cosmic-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.cosmic-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.cosmic-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.cosmic-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

  securecore-main:
    name: Build securecore main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: securecore/recipe-securecore-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  securecore-main-sealed:
    name: Build securecore main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: securecore-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.securecore-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.securecore-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.securecore-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.securecore-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

  iot-main:
    name: Build iot main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: iot/recipe-iot-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  iot-main-sealed:
    name: Build iot main sealed
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: iot-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.iot-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.iot-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.iot-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.iot-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}
