# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: build-secureblue
permissions: {}
on:
  workflow_call:
    inputs:
      recipe:
        type: string
        required: true
      rechunk:
        type: boolean
        required: false
        default: false
    secrets:
      SIGNING_SECRET:
        required: true
      KERNEL_PRIVKEY:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.recipe }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build secureblue
    runs-on: ubuntu-24.04
    environment: Build
    outputs:
      IMAGE_DIGEST: ${{ steps.image_manifest_metadata.outputs.IMAGE_DIGEST }}
      FULL_IMAGE_REF: ${{ steps.image_manifest_metadata.outputs.FULL_IMAGE_REF }}
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    steps:
      - name: Enable egress auditing
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install yq

      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Gather image data from recipe
        shell: bash
        env:
          RECIPE: ${{ inputs.recipe }}
        run: |
          echo "REGISTRY=ghcr.io/secureblue" >> "${GITHUB_ENV}"
          echo "IMAGE_NAME=$(yq -r '."name"' "./recipes/${RECIPE}")" >> "${GITHUB_ENV}"
          echo "BASE_IMAGE=$(yq -r '."base-image"' "./recipes/${RECIPE}")" >> "${GITHUB_ENV}"
          echo "BASE_IMAGE_VERSION=$(yq -r '."image-version"' "./recipes/${RECIPE}")" >> "${GITHUB_ENV}"

      - name: Verify base image provenance
        shell: bash
        run: |
          if [[ "$BASE_IMAGE" != ghcr.io/secureblue/* ]]; then
            echo "Base image isn't secureblue. Skipping."
            exit 0
          fi

          go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.7.1
          go install github.com/google/go-containerregistry/cmd/crane@v0.20.6
          DIGEST=$(~/go/bin/crane digest "${BASE_IMAGE}:${BASE_IMAGE_VERSION}")
          ~/go/bin/slsa-verifier verify-image --source-uri 'github.com/secureblue/secureblue' "${BASE_IMAGE}:${BASE_IMAGE_VERSION}@${DIGEST}"

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: 'v2.6.0'

      - name: Verify base image
        shell: bash
        run: |
          if [[ "$IMAGE_NAME" == 'securecore-main-hardened' || "$IMAGE_NAME" == 'iot-main-hardened' ]]; then
            echo "Upstream isn't signed. Skipping."
            exit 0
          fi

          UPSTREAM_CONTAINER="${BASE_IMAGE}:${BASE_IMAGE_VERSION}"
          if [[ "$BASE_IMAGE" == ghcr.io/secureblue/* ]]; then
            UPSTREAM_PUBKEY='./cosign.pub'
          else
            UPSTREAM_PUBKEY='./files/system/etc/pki/containers/quay.io-fedora-ostree-desktops.pub'
          fi
          if ! cosign verify --key "${UPSTREAM_PUBKEY}" "${UPSTREAM_CONTAINER}" | jq; then
            echo "NOTICE: Verification failed. Please ensure your public key is correct."
            exit 1
          fi

      - name: Build secureblue
        uses: blue-build/github-action@9ba737d93ffa82d7cd6826162c7bc3a2648ae73d # v1.10.3
        env:
          KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}
        with:
          cli_version: v0.9.28
          recipe: ${{ inputs.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          squash: true
          build_chunked_oci: ${{ inputs.rechunk }}
          max_layers: 128
          skip_checkout: true
          use_cache: false
          retry_push_count: 3
          verify_install: true

      - name: Install regctl
        uses: regclient/actions/regctl-installer@1b705e32d40851370799ea5814e83d0a5f6a70dc # v0.1.0

      - name: Parse image manifest
        id: image_manifest_metadata
        shell: bash
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          PR_EVENT_NUMBER: ${{ github.event.number }}
        run: |
          case "$GITHUB_REF" in
            refs/heads/"$DEFAULT_BRANCH") image_tag='latest' ;;
            refs/pull/*) image_tag="pr-${PR_EVENT_NUMBER}-43" ;;
            *) image_tag="br-${GITHUB_REF_NAME}-43" ;;
          esac
          FULL_IMAGE_REF="${REGISTRY}/${IMAGE_NAME}:${image_tag}"
          IMAGE_DIGEST="$(regctl image digest "${FULL_IMAGE_REF}")"
          echo "FULL_IMAGE_REF=${FULL_IMAGE_REF}" >> "${GITHUB_OUTPUT}"
          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [bluebuild]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.bluebuild.outputs.FULL_IMAGE_REF }}
      digest: ${{ needs.bluebuild.outputs.IMAGE_DIGEST }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
