# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: build
permissions: {}
on:
  schedule:
    - cron: "00 6 * * *" # build at 6:00 UTC every day

  push:
    branches-ignore: # don't rebuild for dependabot
      - 'dependabot/**'
      - 'create-pull-request/**'
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  workflow_dispatch: # allow manually triggering builds
    inputs:
      clear-plan:
        description: 'Clear previous layer plan?'
        type: boolean
        required: true
        default: false

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  silverblue-main:
    name: Build silverblue main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-silverblue-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  kinoite-main:
    name: Build kinoite main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-kinoite-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  sericea-main:
    name: Build sericea main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-sericea-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  cosmic-main:
    name: Build cosmic main
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-cosmic-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  silverblue-nvidia:
    name: Build silverblue nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: silverblue-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-silverblue-nvidia.yml
          - general/recipe-silverblue-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  kinoite-nvidia:
    name: Build kinoite nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: kinoite-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-kinoite-nvidia.yml
          - general/recipe-kinoite-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  sericea-nvidia:
    name: Build sericea nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: sericea-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-sericea-nvidia.yml
          - general/recipe-sericea-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  cosmic-nvidia:
    name: Build cosmic nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: cosmic-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-cosmic-nvidia.yml
          - general/recipe-cosmic-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  securecore-main:
    name: Build securecore main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: securecore/recipe-securecore-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  securecore-nvidia:
    name: Build securecore nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: securecore-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - securecore/recipe-securecore-nvidia.yml
          - securecore/recipe-securecore-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  securecore-zfs-main:
    name: Build securecore zfs main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: securecore-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: securecore/recipe-securecore-zfs-main.yml
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  securecore-zfs-nvidia:
    name: Build securecore zfs nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: securecore-zfs-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - securecore/recipe-securecore-zfs-nvidia.yml
          - securecore/recipe-securecore-zfs-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  iot-main:
    name: Build iot main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: iot/recipe-iot-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  iot-nvidia:
    name: Build iot nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: iot-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - iot/recipe-iot-nvidia.yml
          - iot/recipe-iot-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  iot-zfs-main:
    name: Build iot zfs main images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: iot-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: iot/recipe-iot-zfs-main.yml
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  iot-zfs-nvidia:
    name: Build iot zfs nvidia images
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    needs: iot-zfs-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      fail-fast: false 
      matrix:
        recipe:
          - iot/recipe-iot-zfs-nvidia.yml
          - iot/recipe-iot-zfs-nvidia-open.yml
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}
