# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: installer-checksum
permissions: {}
on: 
  pull_request:
    branches:
      - live
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-installer-checksum:
    name: Installer Checksum Verification
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Verify checksum
        shell: bash
        env:
          INSTALL_SCRIPT: files/system/usr/share/secureblue/install_secureblue.sh
          EXAMPLE_BUTANE: docs/example.butane
        run: |
          INSTALLER_CHECKSUM=$(sha256sum $INSTALL_SCRIPT | awk '{ print $1 }')
          BUTANE_CHECKSUM=$(grep -oP 'sha256-\K[a-f0-9]{64}' $EXAMPLE_BUTANE)
          if [ "$INSTALLER_CHECKSUM" != "$BUTANE_CHECKSUM" ]; then
            echo "Checksum mismatch."
            echo "Installer checksum: $INSTALLER_CHECKSUM"
            echo "Butane checksum: $BUTANE_CHECKSUM"
            exit 1
          fi
