# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: RPM GPG key check

permissions: {}

on:
  pull_request:
    paths:
      - '**.repo'
      - '**/rpm-gpg/*'
      - 'files/scripts/**'
      - 'tools/**'
  schedule:
    - cron: "00 3 * * *" # run at 3:00 UTC every day
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rpm-gpg:
    name: Check RPM repo consistency
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Check RPM repo keys
        run: tools/check_repo_keys.py
