# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: integ-tests
permissions: {}
on:
  schedule:
    - cron: "00 7 * * *" # run at 7:00 UTC every day

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run integration tests
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule'
    runs-on: ubuntu-24.04
    permissions:
      contents: read # read repo contents
      packages: write # push integration test image
      id-token: write # generate token for signing
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run integration tests
        uses: secureblue/bootc-integration-test-action@2236e712456801cd0bd47626733e95a180e38675 # v0.0.10
        with:
          registry: ghcr.io/secureblue
          image: silverblue-main-hardened
          token: ${{ secrets.GITHUB_TOKEN }}
          tests: |
            ./.github/workflows/integration_tests/check_audit_results.sh
            ./.github/workflows/integration_tests/check_cleanup.sh
            ./.github/workflows/integration_tests/check_flatpak_setup.sh
            ./.github/workflows/integration_tests/check_unbound_migration.sh
            ./.github/workflows/integration_tests/validate_systemd_unit_files.sh
          data-files: |
            ./.github/workflows/integration_tests/expected-audit-silverblue-main-hardened.txt
