# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: integ-tests
permissions: {}
on:
  schedule:
    - cron: "00 7 * * *" # run at 7:00 UTC every day

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run integration tests
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule'
    runs-on: ubuntu-24.04
    permissions:
      contents: read # read repo contents
      packages: write # push integration test image
      id-token: write # generate token for signing
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Run integration tests
        uses: secureblue/bootc-integration-test-action@56f1a17e4ab15b0feaed849d036686e3ec7adc4b # v0.0.9
        with:
          registry: ghcr.io/secureblue
          image: silverblue-main-hardened
          token: ${{ secrets.GITHUB_TOKEN }}
          tests: |
            ./.github/workflows/integration_tests/check_audit_results.sh
            ./.github/workflows/integration_tests/check_cleanup.sh
            ./.github/workflows/integration_tests/check_flatpak_setup.sh
            ./.github/workflows/integration_tests/check_unbound_migration.sh
            ./.github/workflows/integration_tests/validate_systemd_unit_files.sh
          data-files: |
            ./.github/workflows/integration_tests/expected-audit-silverblue-main-hardened.txt
