# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: just-lint
permissions: {}
on:
  pull_request:
    branches:
      - live
      - staging
    paths:
      - "**.just"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Just lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false 

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint justfiles
        run: |          
          sudo apt-get install pipx
          pipx install rust-just
          find "./files/justfiles" -type f -name "*.just" | while read -r file; do
            echo "Checking syntax: $file"
            just --unstable --fmt --check -f $file || { exit 1; }
          done
