name: PR Approvals

permissions: read-all

on:
  pull_request:

jobs:
  pr-approvals:
    name: PR Approvals
    runs-on: ubuntu-24.04 
    permissions:
      contents: read
    env:
      approvers:
    steps:
      - uses: secureblue/approvals-action@ce28f64903343583dd92c84bffedba124d3a6c95 # v0.1.0
        id: approvers
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-required: 2
          approvers: |
            EsseLowNitro
            fiftydinar
            RoyalOughtness
            mintpilo
            mkkvcs
            RKNF404
            Rubiginosa
            ShadowSlayer1441
            spaceoden
            TheHooly
            WavyEbuilder
            HastD
            pxlkng
