name: PR Approvals

on:
  pull_request:

jobs:
  pr-approvals:
    name: PR Approvals
    runs-on: ubuntu-latest  
    env:
      approvers:
    steps:
      - uses: secureblue/approvals-action@649991bf3a243bfe8c95cd1e9858ed923cb73b21 # v0.0.2
        id: approvers
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-required: 2
          approvers: |
            EsseLowNitro
            fiftydinar
            RoyalOughtness
            mintpilo
            mkkvcs
            RKNF404
            Rubiginosa
            ShadowSlayer1441
            spaceoden
            TheHooly
            WavyEbuilder
