# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: pr-build-nvidia

permissions: {}

on:
  pull_request:
    branches:
      - live
      - staging
    paths:
      - '**nvidia**'
      - './.github/workflows/pr_build.yml'
      - '!**.md'
      - '!.github/**'

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: PR build
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: read # Needed to read base image manifests
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-silverblue-nvidia-open.yml
          - general/recipe-silverblue-nvidia.yml
    uses: ./.github/workflows/pr_build.yml
    with:
      recipe: ${{ matrix.recipe }}
