# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
# SPDX-License-Identifier: Apache-2.0

name: build-pullrequest

permissions: {}

on:
  workflow_call:
    inputs:
      recipe:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.recipe }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: PR build
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: read # Needed to read base image manifests

    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Runner setup
        uses: ./.github/workflows/shared-runner-setup
        with:
          recipe: ${{ inputs.recipe }}

      - name: Set up test keys
        id: test_keys
        shell: bash
        run: |
          cp ./.github/workflows/public_key.der.test ./files/system/etc/pki/akmods/certs/akmods-secureblue.der
          {
            echo 'kernel_privkey<<EOF'
            cat ./.github/workflows/private_key.priv.test
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

      - name: Build secureblue
        uses: blue-build/github-action@9ba737d93ffa82d7cd6826162c7bc3a2648ae73d # v1.10.3
        env:
          KERNEL_PRIVKEY: ${{ steps.test_keys.outputs.kernel_privkey }}
        with:
          cli_version: v0.9.28
          recipe: ${{ inputs.recipe }}
          push: false
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          squash: true
          skip_checkout: true
          verify_install: true
