# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: pr-build-main

permissions: {}

on:
  pull_request:
    branches:
      - live
      - staging
    paths:
      - 'cosign.pub'
      - 'files/scripts/**'
      - 'files/system/kinoite/**'
      - 'files/system/sericea/**'
      - 'files/system/server/**'
      - 'modules/**'
      - 'recipes/**'
      - '!**nvidia**'
      - '!**zfs**'
      - '!**.md'

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: PR build
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: read # Needed to read base image manifests
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - general/recipe-cosmic-main.yml
          - general/recipe-kinoite-main.yml
          - general/recipe-sericea-main.yml
          # general/recipe-silverblue-main already covered by pr_build_minimal.yml
          - securecore/recipe-securecore-main.yml
          - iot/recipe-iot-main.yml
    uses: ./.github/workflows/pr_build.yml
    with:
      recipe: ${{ matrix.recipe }}
