# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: build-pullrequest

permissions: {}

on:
  workflow_call:
    inputs:
      recipe:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.recipe }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: PR build
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Enable egress auditing
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Free disk space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo docker image prune --all --force || true
          sudo swapoff -a || true
          sudo rm -f /mnt/swapfile || true

      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Gather image data from recipe
        shell: bash
        env:
          RECIPE: ${{ inputs.recipe }}
        run: |
          echo "IMAGE_NAME=$(grep '^name:' "./recipes/${RECIPE}" | sed 's/^name: //')" >> "$GITHUB_ENV"
          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' "./recipes/${RECIPE}" | sed 's/^image-version: //')" >> "$GITHUB_ENV"
          BASE_IMAGE=$(grep '^base-image:' "./recipes/${RECIPE}" | sed 's/^base-image: //')
          echo "BASE_IMAGE_NAME=$(echo "$BASE_IMAGE" | sed 's/.*\/.*\///')" >> "$GITHUB_ENV"

      - name: Verify base image provenance
        shell: bash
        run: |
          if [[ "$BASE_IMAGE_NAME" != *hardened* ]]; then
            echo "Base image isn't secureblue. Skipping."
            exit 0
          fi

          go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.7.1
          go install github.com/google/go-containerregistry/cmd/crane@v0.20.6
          DIGEST=$(~/go/bin/crane digest "ghcr.io/secureblue/${BASE_IMAGE_NAME}:latest")
          ~/go/bin/slsa-verifier verify-image --source-uri github.com/secureblue/secureblue ghcr.io/secureblue/${BASE_IMAGE_NAME}:latest@"${DIGEST}"

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: 'v2.6.0'

      - name: Install the slsa-verifier
        uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1

      - name: Verify base image
        shell: bash
        run: |
          if [[ "$IMAGE_NAME" == 'securecore-main-hardened' || "$IMAGE_NAME" == 'iot-main-hardened' ]]; then
            echo "Upstream isn't signed. Skipping."
            exit 0
          fi

          UPSTREAM_CONTAINER="${BASE_IMAGE_NAME}:${IMAGE_MAJOR_VERSION}"
          if [[ "$IMAGE_NAME" != *nvidia* && "$IMAGE_NAME" != *zfs* ]]; then
            UPSTREAM_REGISTRY='quay.io/fedora-ostree-desktops'
            UPSTREAM_PUBKEY='https://gitlab.com/fedora/ostree/ci-test/-/raw/main/quay.io-fedora-ostree-desktops.pub'
          else
            UPSTREAM_REGISTRY='ghcr.io/secureblue'
            UPSTREAM_PUBKEY='https://raw.githubusercontent.com/secureblue/secureblue/refs/heads/live/cosign.pub'
          fi
          if ! cosign verify --key "${UPSTREAM_PUBKEY}" "${UPSTREAM_REGISTRY}/${UPSTREAM_CONTAINER}" | jq; then
            echo "NOTICE: Verification failed. Please ensure your public key is correct."
            exit 1
          fi

      - name: Set container policy to validate Blue-Build cli signature
        shell: bash
        run: |
          POLICY_FILE="/etc/containers/policy.json"
          echo "policy:"
          cat "${POLICY_FILE}"
          CLI_IMAGE_REGISTRY="ghcr.io/blue-build/cli"
          MODULES_IMAGE_REGISTRY="ghcr.io/blue-build/modules"
          MODULES_SCRIPT_IMAGE_REGISTRY="${MODULES_IMAGE_REGISTRY}/script"
          CLI_IMAGE_PUBKEY="/etc/pki/containers/blue-build-cli.pub"
          MODULES_IMAGE_PUBKEY="/etc/pki/containers/blue-build-modules.pub"
          sudo mkdir -p /etc/pki/containers
          sudo curl -Lo "${CLI_IMAGE_PUBKEY}" https://raw.githubusercontent.com/blue-build/cli/refs/heads/main/cosign.pub
          sudo curl -Lo "${MODULES_IMAGE_PUBKEY}" https://raw.githubusercontent.com/blue-build/modules/refs/heads/main/cosign.pub

          # add cli pubkey
          jq --arg cli_image_registry "${CLI_IMAGE_REGISTRY}" \
            --arg cli_image_pubkey "${CLI_IMAGE_PUBKEY}" \
            --arg modules_image_registry "${MODULES_IMAGE_REGISTRY}" \
            --arg modules_script_image_registry "${MODULES_SCRIPT_IMAGE_REGISTRY}" \
            --arg modules_image_pubkey "${MODULES_IMAGE_PUBKEY}" \
            '.transports.docker //= {} |
            .transports.docker[$cli_image_registry] = [
                {
                    "type": "sigstoreSigned",
                    "keyPath": $cli_image_pubkey,
                    "signedIdentity": { 
                        "type": "matchRepository"
                    }
                }
            ] |
            .transports.docker[$modules_image_registry] = [
                {
                    "type": "sigstoreSigned",
                    "keyPath": $modules_image_pubkey,
                    "signedIdentity": { 
                        "type": "matchRepository"
                    }
                }
            ] |
            .transports.docker[$modules_script_image_registry] = [
                {
                    "type": "sigstoreSigned",
                    "keyPath": $modules_image_pubkey,
                    "signedIdentity": { 
                        "type": "matchRepository"
                    }
                }
            ]' "${POLICY_FILE}" > POLICY.tmp
          sudo mv POLICY.tmp "${POLICY_FILE}"

      - name: Determine Vars
        id: build_vars
        shell: bash
        env:
          RECIPE: ${{ inputs.recipe }}
        run: |
          RECIPE_PATH=""
          if [ -f "./config/${RECIPE}" ]; then
            RECIPE_PATH="./config/${RECIPE}"
          else
            RECIPE_PATH="./recipes/${RECIPE}"
          fi
          echo "recipe_path=${RECIPE_PATH}" >> "${GITHUB_OUTPUT}"

      - name: Install BlueBuild
        shell: bash
        run: |
          set -euo pipefail
          CLI_INSTALLER_IMAGE="ghcr.io/blue-build/cli:v0.9.26-installer"
          docker pull "${CLI_INSTALLER_IMAGE}"
          CLI_INSTALLER_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' "${CLI_INSTALLER_IMAGE}")
          slsa-verifier verify-image "${CLI_INSTALLER_IMAGE}" \
              --source-uri github.com/blue-build/cli \
              --source-tag v0.9.26
          sudo docker create \
            --name blue-build-installer \
            "${CLI_INSTALLER_IMAGE}"
          sudo docker cp blue-build-installer:/out/bluebuild /usr/bin/bluebuild
          sudo docker rm blue-build-installer
          bluebuild --version

      - name: Build Image
        shell: bash
        env:
          RECIPE_PATH: ${{ steps.build_vars.outputs.recipe_path }}
          RUST_LOG_STYLE: always
          CLICOLOR_FORCE: '1'
          GH_PR_EVENT_NUMBER: ${{ github.event.number }}
        run: |
          cp ./.github/workflows/public_key.der.test ./files/system/etc/pki/akmods/certs/akmods-secureblue.der
          KERNEL_PRIVKEY=$(< ./.github/workflows/private_key.priv.test)
          export KERNEL_PRIVKEY

          BUILD_OPTS="--build-driver podman --squash"
          bluebuild build -v ${BUILD_OPTS} "${RECIPE_PATH}"
