# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: pr-build-minimal

permissions: {}

on:
  pull_request:
    branches:
      - live
      - staging
    paths-ignore:
      - "**.md"

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: PR build (general/recipe-silverblue-main.yml)
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: read # Needed to read base image manifests
    uses: ./.github/workflows/pr_build.yml
    with:
      recipe: general/recipe-silverblue-main.yml
