# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: verify-provenance
permissions: {}
on:
  schedule:
    - cron: "00 15 * * *" # run at 15:00 UTC every day

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-provenance:
    name: Verify provenance
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule'
    runs-on: ubuntu-slim
    permissions:
      packages: read # needed to pull images
    steps:
      - name: Install deps
        shell: bash
        run: |
          go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.7.1
          go install github.com/google/go-containerregistry/cmd/crane@v0.20.6
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Verify provenance
        shell: bash
        run: |
          images=(
            silverblue-main-hardened
            silverblue-nvidia-hardened
            silverblue-nvidia-open-hardened
            kinoite-main-hardened
            kinoite-nvidia-hardened
            kinoite-nvidia-open-hardened
            sericea-main-hardened
            sericea-nvidia-hardened
            sericea-nvidia-open-hardened
            cosmic-main-hardened
            cosmic-nvidia-hardened
            cosmic-nvidia-open-hardened
            securecore-main-hardened
            securecore-nvidia-hardened
            securecore-nvidia-open-hardened
            securecore-zfs-main-hardened
            securecore-zfs-nvidia-hardened
            securecore-zfs-nvidia-open-hardened
          )

          for image in "${images[@]}"; do
            image_url="ghcr.io/secureblue/${image}:latest"
            digest=$(crane digest "${image_url}")
            echo "Verifying provenance for ${image_url}@${digest}..."
            slsa-verifier verify-image --source-uri 'github.com/secureblue/secureblue' "${image_url}@${digest}"
          done
