# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: build-pullrequest
permissions: {}
on:
  pull_request:
    branches:
      - live
      - staging
    paths-ignore:
      - "**.md"
jobs:
  bluebuild:
    name: PR build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false 
      matrix:
        recipe:
          - general/recipe-cosmic-main.yml
          - general/recipe-sericea-main.yml
          - general/recipe-kinoite-main.yml
          - general/recipe-silverblue-main.yml
          - general/recipe-silverblue-nvidia.yml
          - general/recipe-silverblue-nvidia-open.yml
          - securecore/recipe-securecore-zfs-main.yml
          - securecore/recipe-securecore-zfs-nvidia.yml
          - securecore/recipe-securecore-zfs-nvidia-open.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Gather image data from recipe
        shell: bash
        env:
          RECIPE: ${{ matrix.recipe }}
        run: |
          echo "IMAGE_NAME=$(grep '^name:' ./recipes/${RECIPE} | sed 's/^name: //')" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' ./recipes/${RECIPE} | sed 's/^image-version: //')" >> $GITHUB_ENV
          BASE_IMAGE=$(grep '^base-image:' ./recipes/${RECIPE} | sed 's/^base-image: //')
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV

      - name: Maximize build space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Determine Vars
        id: build_vars
        shell: bash
        env:
          RECIPE: ${{ matrix.recipe }}
        run: |
          RECIPE_PATH=""
          if [ -f "./config/${RECIPE}" ]; then
            RECIPE_PATH="./config/${RECIPE}"
          else
            RECIPE_PATH="./recipes/${RECIPE}"
          fi
          echo "recipe_path=${RECIPE_PATH}" >> ${GITHUB_OUTPUT}
      
      - name: Retrieve Test Signing Key
        shell: bash
        run: |
          cp ./.github/workflows/private_key.priv.test ./files/scripts/certs/private_key.priv
          cp ./.github/workflows/public_key.der.test ./files/system/etc/pki/akmods/certs/akmods-secureblue.der

      - name: Install BlueBuild
        shell: bash
        env:
          CLI_VERSION_TAG: ${{ steps.build_vars.outputs.cli_version }}
        run: |
          docker create \
            --name blue-build-installer \
            ghcr.io/blue-build/cli:v0.9.20-installer
          docker cp blue-build-installer:/out/bluebuild /usr/local/bin/bluebuild
          docker rm blue-build-installer
          bluebuild --version

      - name: Build Image
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        env:
          RECIPE_PATH: ${{ steps.build_vars.outputs.recipe_path }}
          RUST_LOG_STYLE: always
          CLICOLOR_FORCE: '1'
          GH_PR_EVENT_NUMBER: ${{ github.event.number }}
        run: |
          BUILD_OPTS="--build-driver podman --squash"
          bluebuild build -v ${BUILD_OPTS} ${RECIPE_PATH}
          
