# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Python linters
permissions: {}
on:
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/python-lint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  linters:
    name: Python linters
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          tmpfile=$(mktemp)
          cat <<'EOF' > "${tmpfile}"
          pip==26.1.1 \
            --hash=sha256:99cb1c2899893b075ff56e4ed0af55669a955b49ad7fb8d8603ecdaf4ed653fb

          blessed==1.42.0 \
            --hash=sha256:f96c4a6dc664b48e0b832fa732acc16df67abd30f0ec35babf99025982f21852
          editor==1.8.0 \
            --hash=sha256:7d47ff88ae6c5f6c43d28c30b6f7fd59a24741175a1771ab06c969d946d7dfd0
          inquirer==3.4.1 \
            --hash=sha256:717bf146d547b595d2495e7285fd55545cff85e5ce01decc7487d2ec6a605412
          jinxed==2.0.0 \
            --hash=sha256:b3df1be5262a37145ef42875a8bbf918f1a563fbd035359650dd9fc0bb2b9294
          readchar==4.2.2 \
            --hash=sha256:92daf7e42c52b0787e6c75d01ecfb9a94f4ceff3764958b570c1dddedd47b200
          rpm==0.4.0 \
            --hash=sha256:0ef697cb5fb73bf9300a13d423529d7ec215239bf95c5ecb145e6610645f6067
          ruff==0.15.14 \
            --hash=sha256:715c543cf450c4888251f91c52f1942a800541d9bddd7ac060aa4e6b77ae7cba
          runs==1.3.0 \
            --hash=sha256:e71a551cfa8da9ef882cac1d5a108bda78c9edee5b8d87e37c1003da5b6a7bed
          ty==0.0.38 \
            --hash=sha256:375d3a964c6b4aea2e9237fdb5eb9ed03dc43088986a94209a28a4ea3b62001c
          wcwidth==0.7.0 \
            --hash=sha256:5d69154c429a82910e241c738cd0e2976fac8a2dd47a1a805f4afed1c0f136f2
          xmod==1.10.0 \
            --hash=sha256:bebf8493b7ac63097401590a329c9ed20da224de0583a522e7ccb634af122f5a
          EOF

          python -m pip install --require-hashes -r "${tmpfile}"

      - name: Run Ruff (linter)
        run: ruff check --output-format=github

      - name: Check code formatting
        run: ruff format --diff

      - name: Run Ty (type-checker)
        run: ty check --output-format=github
