# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: ruff
permissions: {}
on:
  pull_request:
    paths:
      - '**.py'
      - 'ruff.toml'
      - '.github/workflows/ruff.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff (Python linter)
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          echo '
          pip==25.2 \
            --hash=sha256:6d67a2b4e7f14d8b31b8b52648866fa717f45a1eb70e83002f4331d07e953717

          ruff==0.13.0 \
            --hash=sha256:03447f3d18479df3d24917a92d768a89f873a7181a064858ea90a804a7538991
          ' > requirements.txt

          python -m pip install --require-hashes -r requirements.txt

      - name: Run Ruff
        run: ruff check --output-format=github .

      - name: Check code formatting
        run: ruff format --diff
