# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: ruff
permissions: {}
on:
  pull_request:
    paths:
      - '**.py'
      - 'ruff.toml'
      - '.github/workflows/ruff.yml'
jobs:
  ruff:
    name: Ruff (Python linter)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          echo '
          pip==25.2 \
            --hash=sha256:6d67a2b4e7f14d8b31b8b52648866fa717f45a1eb70e83002f4331d07e953717

          ruff==0.13.0 \
            --hash=sha256:03447f3d18479df3d24917a92d768a89f873a7181a064858ea90a804a7538991
          ' > requirements.txt
          
          python -m pip install --require-hashes -r requirements.txt

      - name: Run Ruff
        run: ruff check --output-format=github .

      - name: Check code formatting
        run: ruff format --diff
