# SPDX-FileCopyrightText: Copyright 2026 The Secureblue Authors
# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
#
# SPDX-License-Identifier: Apache-2.0

name: "Sign UKI addons"

env:
  FEDORA_RELEASE: "44"

on:
  # This only needs changing when the kargs change.
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  uki-sign-uki-addons:
    name: "Build and UKI-sign UKI addons"
    runs-on: "ubuntu-26.04"
    environment: UKIBuild
    if: github.triggering_actor == 'royaloughtness'
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: write # Needed to publish images
    outputs:
      IMAGE_DIGEST: ${{ steps.push.outputs.digest }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up runner"
        uses: $/.github/workflows/shared-runner-setup

      - name: "Log in to registry"
        uses: redhat-actions/podman-login@50c2d9a331bb67c8fdab99b86455fad05e2e3252 # v2.0
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get secure boot signing key"
        run: |
          mkdir -p /tmp/keys
          printenv UKI_DB_KEY > /tmp/keys/key
          cp uki/keys/db/db.pem /tmp/keys/crt
        env:
          UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}

      - name: "Build container image"
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: "uki-addons"
          tags: "latest ${{ github.run_number }}"
          containerfiles: "uki/Containerfile.addons"
          oci: true
          build-args: |
            RELEASE=${{ env.FEDORA_RELEASE }}
          extra-args: |
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Clean up secure boot signing key"
        if: always()
        run: rm -vrf /tmp/keys

      - name: "Push to registry"
        id: push
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: "uki-addons"
          tags: "latest ${{ github.run_number }}"

  cosign-uki-addons:
    needs: uki-sign-uki-addons
    name: "Cosign uki addons"
    environment: Build
    runs-on: "ubuntu-26.04"
    permissions:
      contents: read # Needed to pull the repo for the build
      packages: write # Needed to sign images
    steps:
      - name: "Check out repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up runner"
        uses: $/.github/workflows/shared-runner-setup
        with:
          needs_cosign: true

      - name: "Log in to registry"
        uses: redhat-actions/podman-login@50c2d9a331bb67c8fdab99b86455fad05e2e3252 # v2.0
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Cosign container image"
        run: |
          cosign sign -y --key env://COSIGN_KEY ghcr.io/${GITHUB_REPOSITORY_OWNER}/uki-addons@${DIGEST}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
          DIGEST: ${{ needs.uki-sign-uki-addons.outputs.IMAGE_DIGEST }}

  provenance:
    needs: uki-sign-uki-addons
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    # Currently this must be referenced by tag, not by hash:
    # https://github.com/slsa-framework/slsa-github-generator?tab=readme-ov-file#referencing-slsa-builders-and-generators
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0 # zizmor: ignore[unpinned-uses]
    with:
      image: "ghcr.io/${{ github.repository_owner }}/uki-addons"
      digest: ${{ needs.uki-sign-uki-addons.outputs.IMAGE_DIGEST }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
