---
name: Super-Linter

on:
  pull_request:
    branches:
      - live
      - staging
      - next
      - testing

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Super-Linter
    runs-on: ubuntu-26.04

    permissions:
      contents: read # to clone the repository

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          LINTER_RULES_PATH: .
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          MULTI_STATUS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}