# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: run-tests
permissions: {}
on:
  pull_request:
    branches:
      - live
      - staging
      - next
    paths-ignore:
      - "**.md"
  workflow_dispatch: # allow manually triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    name: Install Bats and run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 #v4.0.0
        with:
           support-path: "${{ github.workspace }}/.bats/bats-support"
           assert-path: "${{ github.workspace }}/.bats/bats-assert"
           detik-path: "${{ github.workspace }}/.bats/bats-detik"
           file-path: "${{ github.workspace }}/.bats/bats-file"

      - name: Install just
        env:
          OS_ARCH: x86_64
        run: |
          sudo --preserve-env=OS_ARCH bash files/scripts/manuallyinstalljust.sh

      - name: Run tests
        shell: bash
        env:
          INSTALL_SCRIPT: files/system/usr/share/secureblue/install_secureblue.sh
          BATS_LIB_PATH: "${{ github.workspace }}/.bats"
        run: |
          bats --timing --trace --verbose-run -r .github/workflows/tests
