name: trivy-scan
on:
  schedule:
    - cron: "00 8 * * *" # build at 8:00 UTC every day 
                         # 120 minutes after secureblue images start building
  push:
    branches:
      - live
    paths-ignore:
      - "**.md"

  workflow_dispatch: # allow manually triggering builds
jobs:
  build:
    name: Trivy
    if: github.triggering_actor == 'royaloughtness' || ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'push' }} 
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          image-ref: 'ghcr.io/secureblue/silverblue-main-hardened:latest'
          format: template
          scanners: vuln,secret,misconfig
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          timeout: 30m0s
          skip-dirs: "/sysroot/ostree"
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@fca7ace96b7d713c7035871441bd52efbe39e27e # v3.28.19
        with:
          sarif_file: trivy-results.sarif
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Trivy scan SARIF
          path: trivy-results.sarif
