# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: trivy
permissions: {}
on:
  schedule:
    - cron: "00 8 * * *" # build at 8:00 UTC every day 
                         # 120 minutes after secureblue images start building
  push:
    branches:
      - live
    paths-ignore:
      - "**.md"

  workflow_dispatch: # allow manually triggering builds

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Trivy
    if: github.triggering_actor == 'royaloughtness' || github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-slim
    permissions:
      security-events: write # write findings to github
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          image-ref: 'ghcr.io/secureblue/silverblue-main-hardened:latest'
          format: template
          scanners: vuln,secret,misconfig
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          timeout: 30m0s
          skip-dirs: "/sysroot/ostree"
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        with:
          sarif_file: trivy-results.sarif

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Trivy scan SARIF
          path: trivy-results.sarif
