# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: update-modules
permissions: {}
on:
  schedule:
    - cron: 00 0 * * TUE  # run weekly
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-modules:
    name: Update BlueBuild modules
    runs-on: ubuntu-slim
    permissions:
      contents: write  # needed to create branch
      pull-requests: write  # needed to create pull request

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install jq skopeo

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: true  # zizmor: ignore[artipacked]

      - name: Get image metadata
        id: metadata
        shell: bash
        run: |
          manifest=$(skopeo inspect -n 'docker://ghcr.io/blue-build/modules:latest')

          digest=$(echo "$manifest" | jq -cr '.Digest')
          pattern='^sha256:[0-9A-Fa-f]{64}$'
          if [[ ! $digest =~ $pattern ]]; then
            echo "Error: image digest had value in unexpected format: '${digest}'." >&2
            exit 1
          fi
          echo "digest=${digest}" >> "${GITHUB_OUTPUT}"

          time_created=$(echo "$manifest" | jq -cr '.Created')
          echo "time_created=${time_created}" >> "${GITHUB_OUTPUT}"

          prev_image=$(grep -Eo -m1 '\<ghcr\.io/blue-build/modules@sha256:[[:xdigit:]]+' recipes/common/common-modules.yml)
          prev_time_created=$(skopeo inspect -n "docker://$prev_image" | jq -cr '.Created')
          echo "prev_time_created=${prev_time_created}" >> "${GITHUB_OUTPUT}"

      - name: Get commit list
        id: commits
        shell: bash
        env:
          AUTH_HEADER: "Authorization: Bearer ${{ github.token }}"
          COMMITS_SINCE: ${{ steps.metadata.outputs.prev_time_created }}
          COMMITS_UNTIL: ${{ steps.metadata.outputs.time_created }}
        run: |
          commits=$(curl -fLsS --retry 5 \
            -H "Accept: application/vnd.github+json" \
            -H "${AUTH_HEADER}" \
            --url-query "since=${COMMITS_SINCE}" \
            --url-query "until=${COMMITS_UNTIL}" \
            'https://api.github.com/repos/blue-build/modules/commits' \
            | jq -cr '[.[] | {message: (.commit.message | split("\n") | first), hash: .sha}]')
          commit_count=$(echo "$commits" | jq -cr 'length')
          echo "commits=${commits}" >> "${GITHUB_OUTPUT}"
          echo "commit_count=${commit_count}" >> ${GITHUB_OUTPUT}

      - name: Check if commit list is non-empty
        id: check_commits
        continue-on-error: true
        shell: bash
        env:
          COMMIT_COUNT: ${{ steps.commits.outputs.commit_count }}
        run: |
          if [ "${COMMIT_COUNT}" -eq 0 ]; then
            echo 'No new commits to blue-build/modules since last update; exiting.'
            exit 1
          fi

      - name: Update BlueBuild modules
        if: steps.check_commits.conclusion == 'success'
        shell: bash
        env:
          MODULES_DIGEST: ${{ steps.metadata.outputs.digest }}
        run: |
          find ./recipes -type f -name '*.yml' \
            -execdir sed --sandbox -Ei \
              -e "/\<source: ghcr\.io\/blue-build\/modules@/s/@sha256:.*/@${MODULES_DIGEST}/" \
              '{}' +

      - name: Construct PR body text
        id: pr_body
        if: steps.check_commits.conclusion == 'success'
        shell: bash
        env:
          COMMIT_DATA: ${{ steps.commits.outputs.commits }}
        run: |
          commit_list=$(echo "${COMMIT_DATA}" | jq -cr '.[] | "* `\(.message)` (https://github.com/blue-build/modules/commit/\(.hash))"')
          body_path=$(mktemp)
          cat <<EOF > "${body_path}"
          Automatically update BlueBuild modules to the SHA256 hash of the latest build of [blue-build/modules].

          The following commits were made to blue-build/modules since the last update:

          ${commit_list}

          [blue-build/modules]: https://github.com/blue-build/modules/pkgs/container/modules
          EOF
          echo "body_path=${body_path}" >> "${GITHUB_OUTPUT}"

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0  # v8.1.0
        if: steps.check_commits.conclusion == 'success'
        with:
          add-paths: |
            recipes/*.yml
          commit-message: 'chore(deps): update BlueBuild modules'
          branch: create-pull-request/update-bluebuild-modules
          sign-commits: true
          title: 'chore(deps): update BlueBuild modules'
          body-path: ${{ steps.pr_body.outputs.body_path }}
