# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: update-po
permissions: {}
on:
  schedule:
    - cron: 00 0 * * MON  # run weekly
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-po:
    name: Update PO files
    runs-on: ubuntu-slim
    permissions:
      contents: write  # needed to create branch
      pull-requests: write  # needed to create pull request

    steps:
      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Install gettext
        shell: bash
        run: |
          sudo apt-get install gettext

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: true  # zizmor: ignore[artipacked]

      - name: Update PO files
        shell: bash
        run: |
          python3 files/po/update_po.py

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0  # v8.1.0
        with:
          add-paths: |
            files/po/*.pot
            files/po/*/*.po
          commit-message: 'chore(i18n): update PO files'
          branch: create-pull-request/update-po
          sign-commits: true
          title: 'chore(i18n): update PO files'
          body: |
            Automatically update POT and PO files by running the script `files/po/update_po.py`.

            Translators may need to add new translations to the PO files.
