# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: validate-exec-bit
permissions: {}
on: 
  pull_request:
    branches:
      - live
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-exec-bit:
    name: Validate exec bit
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate exec bit
        shell: bash
        run: |
          executable_paths=(
            "files/system/usr/libexec/*.sh"
            "files/system/usr/libexec/secureblue/*"
            "files/system/usr/bin/*"
            "files/system/kinoite/usr/libexec/secureblue/*"
            "files/system/desktop/usr/libexec/secureblue/*"
          )

          files_missing_exec=()

          for executable_path in "${executable_paths[@]}"; do
            for file in $executable_path; do
              if [ -f "$file" ] && [ ! -x "$file" ]; then
                files_missing_exec+=("$file")
              fi
            done
          done

          if [ ${#files_missing_exec[@]} -ne 0 ]; then
            for file in "${files_missing_exec[@]}"; do
              echo "File missing exec bit: $file"
            done
            exit 1
          else
            exit 0
          fi
